import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("linkDesktop", {
  chat: (prompt) => ipcRenderer.invoke("link:chat", prompt),
  runSkill: (skillName) => ipcRenderer.invoke("link:run-skill", skillName),
  listSkills: () => ipcRenderer.invoke("link:list-skills"),
  listTools: () => ipcRenderer.invoke("link:list-tools"),
  createSharedChannelDraft: (input) => ipcRenderer.invoke("link:shared-channel-draft", input),
  listActiveWork: () => ipcRenderer.invoke("link:list-active-work"),
  decideWork: (id, decision) => ipcRenderer.invoke("link:decide-work", { id, decision }),
  listAutomations: () => ipcRenderer.invoke("link:list-automations"),
  listConnectors: () => ipcRenderer.invoke("link:list-connectors"),
  listCredentials: () => ipcRenderer.invoke("link:list-credentials"),
  saveCredential: (input) => ipcRenderer.invoke("link:save-credential", input),
  updateConnectorStatus: (id, status) => ipcRenderer.invoke("link:update-connector-status", { id, status }),
  listOnboarding: () => ipcRenderer.invoke("link:list-onboarding"),
  updateOnboarding: (input) => ipcRenderer.invoke("link:update-onboarding", input),
  signInAgentControlPlane: () => ipcRenderer.invoke("link:agent-control-plane-sign-in"),
  signOutAgentControlPlane: () => ipcRenderer.invoke("link:agent-control-plane-sign-out"),
  getAgentControlPlaneAuthStatus: () => ipcRenderer.invoke("link:agent-control-plane-auth-status"),
  listHostedAgents: () => ipcRenderer.invoke("link:list-hosted-agents"),
  listWorkspaces: () => ipcRenderer.invoke("link:list-workspaces"),
  searchExplorer: (input) => ipcRenderer.invoke("link:search-explorer", input),
  listChatSessions: () => ipcRenderer.invoke("link:list-chat-sessions"),
  sendChatMessage: (input) => ipcRenderer.invoke("link:send-chat-message", input),
  createChangeRequest: (input) => ipcRenderer.invoke("link:create-change-request", input),
  approveChangeRequest: (id) => ipcRenderer.invoke("link:approve-change-request", id),
  dismissChangeRequest: (id) => ipcRenderer.invoke("link:dismiss-change-request", id),
  listChangeRequests: () => ipcRenderer.invoke("link:list-change-requests"),
  listAgents: () => ipcRenderer.invoke("link:list-agents"),
  sendAgentMessage: (input) => ipcRenderer.invoke("link:send-agent-message", input),
  listWorkboard: (input) => ipcRenderer.invoke("link:workboard-list", input),
  createWorkboardCard: (input) => ipcRenderer.invoke("link:workboard-create-card", input),
  updateWorkboardCard: (input) => ipcRenderer.invoke("link:workboard-update-card", input),
  dispatchWorkboard: (input) => ipcRenderer.invoke("link:workboard-dispatch", input),
  searchPhoneNumbers: (input) => ipcRenderer.invoke("link:phone-search-numbers", input),
  previewPhoneSetup: (input) => ipcRenderer.invoke("link:phone-preview-setup", input),
  provisionPhoneSystem: (input) => ipcRenderer.invoke("link:phone-provision-system", input),
  listMemoryBanks: () => ipcRenderer.invoke("link:list-memory-banks"),
  recallMemory: (input) => ipcRenderer.invoke("link:recall-memory", input),
  listDojoState: () => ipcRenderer.invoke("link:list-dojo-state"),
  auditEvents: () => ipcRenderer.invoke("link:audit-events"),
});
